# Generated by Django 5.1.3 on 2024-12-17 13:50

import FiTrack.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[FiTrack.accounts.validators.MaxSizeValidator(5), FiTrack.accounts.validators.validate_image_extension]),
        ),
    ]
