# Generated by Django 5.1.3 on 2024-12-17 14:15

import FiTrack.workout.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='calories_burned',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Calories burned must be at least 1.'), django.core.validators.MaxValueValidator(10000, message='Calories burned cannot exceed 10,000.')]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(validators=[FiTrack.workout.validators.validate_past_date]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration_minutes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Duration must be at least 1 minute.'), django.core.validators.MaxValueValidator(1440, message='Duration cannot exceed 1440 minutes (24 hours).')]),
        ),
    ]
